### ISSUE TITLE
Reference test cases

### ISSUE THREAD

**Issue by parkan** [multiformats/multihash#27]
We've split out our Scala multihash implementation (from [L-SPACE](https://github.com/mediachain/L-SPACE)) into a little lib: https://github.com/mediachain/scala-multihash

I'd love to add some tests before pushing this up to maven, but it seems silly to reinvent the wheel. Are there any reference test cases I can use to verify our implementation? A csv of `input bytes, algo, output bytes` seems ideal.

**Comment by mseri** [comment]
I am not sure if this can be useful, and it's definitely not the reference set of test-cases, however I did add some multi hash and encoding tests to my haskell implementation while iterating over ideas: https://github.com/mseri/crypto-multihash/blob/master/test/Spec.hs

**Comment by jbenet** [comment]
We're working on a standard test suite. see #32.

I like the idea of having a csv with `input bytes, mh prefix (algo + len), output bytes`.

**Comment by jbenet** [comment]
Added some test cases + scripts to make more in #42

I'm relying on `go-multihash` for these.

**Comment by jbenet** [comment]
@chriscool maybe we can use those test cases with the sharness tests you're making to test the bins. 

- need to check `echo $col2 | multihash -a $col0 -l $col1 -e hex -q == $col3`
- maybe it should test more than just the hex encoding though. may need to be more sophisticated. may want to write than in Go.
- feel free to reformat the scripts to produce different test case file ouput if you need something else. (maybe space delimited instead of commas, etc)

**Comment by chriscool** [comment]
@jbenet yeah I can take a look at that.
It would be nice if you could merge PR #39 first as it improves the sharness framework. I also started using $MULTIHASH_BIN if this environment variable is set and it depends on PR #39.
